
parameters = [
    {'par': 1e-11, 'type': 'Off', 'name': 'void', 'reset': False},
    {'par': 1e-11, 'type': 'Off', 'name': 'void', 'reset': False},
    {'par': 1e-11, 'type': 'Off', 'name': 'void', 'reset': False},
    {'par': 1e-11, 'type': 'Off', 'name': 'void', 'reset': False},
    {'par': 1e-11, 'type': 'Off', 'name': 'void', 'reset': False},
    {'par': 1e-11, 'type': 'Off', 'name': 'void', 'reset': False},
    {'par': 1e-11, 'type': 'Off', 'name': 'void', 'reset': False},
    {'par': 1e-11, 'type': 'Off', 'name': 'void', 'reset': False},
    {'par': 1e-11, 'type': 'Off', 'name': 'void', 'reset': False},
    {'par': 1e-11, 'type': 'Off', 'name': 'void', 'reset': False},
    {'par': 1e-11, 'type': 'Off', 'name': 'void', 'reset': False},
    {'par': 1e-11, 'type': 'Off', 'name': 'void', 'reset': False},
    {'par': 1e-11, 'type': 'Off', 'name': 'void', 'reset': False},
    {'par': 1e-11, 'type': 'Off', 'name': 'void', 'reset': False},
    {'par': 1e-11, 'type': 'Off', 'name': 'void', 'reset': False},
    {'par': 1e-11, 'type': 'Off', 'name': 'void', 'reset': False},
    {'par': 1e-11, 'type': 'Off', 'name': 'void', 'reset': False},
    {'par': 1e-09, 'type': 'ptype', 'name': 'ahp_pw_PFI', 'reset': True, 'modified': True},
    {'par': 1e-10, 'type': 'ntype', 'name': 'bias_posttrace_CC_NFI', 'reset': False, 'modified': True},
    {'par': 1e-10, 'type': 'ptype', 'name': 'bias_posttrace_CC_PFI', 'reset': False, 'modified': True},
    {'par': 5e-11, 'type': 'ntype', 'name': 'ref_posttrace_CC_NFI', 'reset': False, 'modified': True},
    {'par': 1e-11, 'type': 'ntype', 'name': 'bias_sodpi_hthr_CC_NFI', 'reset': False, 'modified': True},
    {'par': 1e-10, 'type': 'ptype', 'name': 'bias_sodpi_hthr_CC_PFI', 'reset': False, 'modified': True},
    {'par': 2e-10, 'type': 'ntype', 'name': 'ref_sodpi_hthr_CC_NFI', 'reset': False, 'modified': True},
    {'par': 1e-11, 'type': 'ntype', 'name': 'bias_sodpi_lthr_CC_NFI', 'reset': False, 'modified': True},
    {'par': 1e-10, 'type': 'ptype', 'name': 'bias_sodpi_lthr_CC_PFI', 'reset': False, 'modified': True},
    {'par': 3e-11, 'type': 'ntype', 'name': 'ref_sodpi_lthr_CC_NFI', 'reset': False, 'modified': True},

    {'par': 5e-09, 'type': 'ptype', 'name': 'tau_posttrace_PFI', 'reset': True, 'modified': True},
    {'par': 1e-09, 'type': 'ptype', 'name': 'gain_posttrace_PFI', 'reset': False, 'modified': True},
    {'par': 1e-08, 'type': 'ntype', 'name': 'w_posttrace_NFI', 'reset': False, 'modified': True},
    {'par': 5e-12, 'type': 'ptype', 'name': 'tau2_sodpi_PFI', 'reset': True, 'modified': True},
    {'par': 1e-11, 'type': 'ptype', 'name': 'gain2_sodpi_PFI', 'reset': False, 'modified': True},
    {'par': 1.5e-11, 'type': 'ntype', 'name': 'tau1_sodpi_NFI', 'reset': True, 'modified': True},
    {'par': 8e-11, 'type': 'ntype', 'name': 'gain1_sodpi_NFI', 'reset': False, 'modified': True},

    {'par': 1e-09, 'type': 'ptype', 'name': 'w_sodpi_PFI', 'reset': False, 'modified': True},

    {'par': 2e-06, 'type': 'ntype', 'name': 'neuron_mon_bias_NFI', 'reset': False, 'modified': True},
    {'par': 3e-11, 'type': 'ntype', 'name': 'neuron_ref_NFI', 'reset': False, 'modified': True},
    {'par': 1e-11, 'type': 'ntype', 'name': 'neuron_starve_NFI', 'reset': True, 'modified': True},
    {'par': 4e-09, 'type': 'ptype', 'name': 'neuron_spkthr_PFI', 'reset': True, 'modified': True},
    {'par': 1e-6, 'type': 'ntype', 'name': 'neuron_tau_NFI', 'reset': True, 'modified': True},
    {'par': 20e-12, 'type': 'ntype', 'name': 'neuron_gain_NFI', 'reset': False, 'modified': True},

    {'par': 1e-15, 'type': 'ntype', 'name': 'ahp_tau_NFI', 'reset': True, 'modified': True},
    {'par': 1e-15, 'type': 'ntype', 'name': 'ahp_gain_NFI', 'reset': False, 'modified': True},
    {'par': 1e-15, 'type': 'ptype', 'name': 'ahp_w_PFI', 'reset': False, 'modified': True},

    {'par': 3e-08, 'type': 'ptype', 'name': 'plastic_right_tau_PFI', 'reset': True, 'modified': True},
    {'par': 3e-08, 'type': 'ptype', 'name': 'plastic_right_gain_PFI', 'reset': False, 'modified': True},
    {'par': 3e-08, 'type': 'ptype', 'name': 'plastic_left_tau_PFI', 'reset': True, 'modified': True},
    {'par': 3e-08, 'type': 'ptype', 'name': 'plastic_left_gain_PFI', 'reset': False, 'modified': True},

    {'par': 1e-15, 'type': 'ptype', 'name': 'static_exc_tau_PFI', 'reset': True, 'modified': True},
    {'par': 1e-15, 'type': 'ptype', 'name': 'static_exc_gain_PFI', 'reset': False, 'modified': True},
    {'par': 1e-15, 'type': 'ntype', 'name': 'static_inh_tau_NFI', 'reset': True, 'modified': True},
    {'par': 1e-15, 'type': 'ntype', 'name': 'static_inh_gain_NFI', 'reset': False, 'modified': True},

    {'par': 1e-15, 'type': 'ptype', 'name': 'neuron_DCcurrent_PFI', 'reset': False, 'modified': True},

    {'par': 1e-10, 'type': 'ntype', 'name': 'learning_bistable_thr_NFI', 'reset': False, 'modified': True},
    {'par': 1e-09, 'type': 'ntype', 'name': 'learning_bias_ota_NFI', 'reset': False, 'modified': True},
    {'par': 2e-06, 'type': 'ntype', 'name': 'learning_mon_bias_NFI', 'reset': False, 'modified': True},
    {'par': 0.0, 'type': 'ptype', 'name': 'learning_bistab_slwup_PFI', 'reset': False, 'modified': True},
    {'par': 0.0, 'type': 'ntype', 'name': 'learning_bistab_slwdw_NFI', 'reset': False, 'modified': True},
    {'par': 5e-11, 'type': 'ntype', 'name': 'learning_w_post_dep_NFI', 'reset': False, 'modified': True},
    {'par': 1e-11, 'type': 'ntype', 'name': 'learning_w_pre_dep_NFI', 'reset': False, 'modified': True},
    {'par': 2e-11, 'type': 'ntype', 'name': 'learning_pre_trace_thr_NFI', 'reset': False, 'modified': True},
    {'par': 1e-10, 'type': 'ptype', 'name': 'learning_bias_scurrcomp_PFI', 'reset': False, 'modified': True},

    {'par': 100e-09, 'type': 'ntype', 'name': 'ssynapse_w_NFI', 'reset': False, 'modified': True},
    {'par': 1e-10, 'type': 'ntype', 'name': 'learning_bias_scurrcomp_NFI', 'reset': False, 'modified': True},
    {'par': 100e-09, 'type': 'ptype', 'name': 'ssynapse_w_PFI', 'reset': False, 'modified': True},

    {'par': 0.0, 'type': 'ntype', 'name': 'learning_pre_trace_thr_low_NFI', 'reset': False, 'modified': True},
    {'par': 1e-11, 'type': 'ptype', 'name': 'learning_dpi_gain_PFI', 'reset': False, 'modified': True},
    {'par': 3e-08, 'type': 'ntype', 'name': 'learning_dpi_w_NFI', 'reset': False, 'modified': True},
    {'par': 1e-11, 'type': 'ptype', 'name': 'learning_dpi_tau_PFI', 'reset': True, 'modified': True},

    {'par': 1e-15, 'type': 'ntype', 'name': 'bypass_tail_w0_NFI', 'reset': False, 'modified': True},
    {'par': 1e-08, 'type': 'ntype', 'name': 'bypass_tail_w1_NFI', 'reset': False, 'modified': True},
    {'par': 2e-07, 'type': 'ptype', 'name': 'norm_bias_PFI', 'reset': False, 'modified': True},

    {'par': 1e-09, 'type': 'ptype', 'name': 'pw_read_pot_PFI', 'reset': True, 'modified': True},
    {'par': 1e-09, 'type': 'ptype', 'name': 'ctrl_pw_read_PFI', 'reset': True, 'modified': True},
    {'par': 1e-09, 'type': 'ptype', 'name': 'pw_read_inh_PFI', 'reset': True, 'modified': True},
    {'par': 1e-09, 'type': 'ptype', 'name': 'ctrl_pw_write_PFI', 'reset': True, 'modified': True},

    {'par': 1e-12, 'type': 'ptype', 'name': 'CF_OFFBIAS_PI', 'reset': False},

    {'par': 1e-06, 'type': 'ptype', 'name': 'CF_BIAS_P_1', 'reset': False},
    {'par': 10e-12, 'type': 'ptype', 'name': 'CF_HYS_P_1', 'reset': False},
    {'par': 1e-12, 'type': 'ntype', 'name': 'CF_REF_L_1', 'reset': False},
    {'par': 1e-11, 'type': 'ntype', 'name': 'CF_REF_H_1', 'reset': False},
    {'par': 1e-6, 'type': 'ptype', 'name': 'CF_PWLK_P_1', 'reset': True},

    {'par': 1e-06, 'type': 'ptype', 'name': 'CF_BIAS_P_2', 'reset': False},
    {'par': 10e-12, 'type': 'ptype', 'name': 'CF_HYS_P_2', 'reset': False},
    {'par': 1e-12, 'type': 'ntype', 'name': 'CF_REF_L_2', 'reset': False},
    {'par': 1e-11, 'type': 'ntype', 'name': 'CF_REF_H_2', 'reset': False},
    {'par': 1e-6, 'type': 'ptype', 'name': 'CF_PWLK_P_2', 'reset': True},

    {'par': 1e-06, 'type': 'ptype', 'name': 'CF_BIAS_P_3', 'reset': False},
    {'par': 10e-12, 'type': 'ptype', 'name': 'CF_HYS_P_3', 'reset': False},
    {'par': 1e-12, 'type': 'ntype', 'name': 'CF_REF_L_3', 'reset': False},
    {'par': 1e-11, 'type': 'ntype', 'name': 'CF_REF_H_3', 'reset': False},
    {'par': 1e-06, 'type': 'ptype', 'name': 'CF_PWLK_P_3', 'reset': True},

    {'par': 1e-15, 'type': 'ptype', 'name': 'param_gen_PFI', 'reset': False},
    {'par': 2e-06, 'type': 'ptype', 'name': 'OTA_BIAS', 'reset': False},
    {'par': 2e-06, 'type': 'ntype', 'name': 'Buffer_drive_NI'}]

get_bin = lambda x, n: format(x, 'b').zfill(n)
flags = [
    {'name': 'handshake_EN', 'value': '1'},
    {'name': 'synapse_hs_delay_config_B', 'value': str(get_bin(0, 4))},
    {'name': 'dev_debug', 'value': '0'},
    {'name': 'nrm_stge_reset', 'value': '0'},
    {'name': 'nrn_targ_en', 'value': '1'},
    {'name': 'syn_targ_en', 'value': '1'},
    {'name': 'dec_ack_disable', 'value': '0'},
    {'name': 'nrn_targ_x', 'value': str(get_bin(0, 5))},
    {'name': 'nrn_targ_y', 'value': str(get_bin(0, 3))},
    {'name': 'syn_targ_x', 'value': str(get_bin(0, 6))},
    {'name': 'syn_targ_y', 'value': str(get_bin(0, 9))},
    {'name': 'dev_use_AMI', 'value': '0'},
    {'name': 'dev_const_read', 'value': '0'},
    {'name': 'dev_write_EFI', 'value': '0'},
    {'name': 'ctrl_syn_state_select_right', 'value': '1'},
    {'name': 'ctrl_syn_state_select_left', 'value': '1'},
    {'name': 'en_plastic_left_inh', 'value': '0'},
    {'name': 'en_plastic_right_inh', 'value': '0'},
    {'name': 'ahp_en_EFO', 'value': '0'},
    {'name': 'TA_EN_1', 'value': '1'},
    {'name': 'TA_EN_2', 'value': '1'},
    {'name': 'CF_EN_ASI_1', 'value': str(get_bin(0, 7))},
    {'name': 'CF_EN_ASI_2', 'value': str(get_bin(0, 3))},
    {'name': 'CF_EN_ASI_3', 'value': str(get_bin(0, 2))},
    {'name': 'paramgen_en_EMB', 'value': '1'},
    {'name': 'learning_en_EMB', 'value': '0'},
]